'use strict'

export const RECEIVE_ALL_CASTLES = 'RECEIVE_ALL_CASTLES';

export const RECEIVE_CASTLE = 'RECEIVE_CASTLE';

export const RECEIVE_CASTLE_REVIEWS = 'RECEIVE_CASTLE_REVIEWS';

export const FETCH_CASTLE_BY_CATEGORY = 'FETCH_CASTLE_BY_CATEGORY';