'use strict'

export const RECEIVE_ALL_CASTLES = 'RECEIVE_ALL_CASTLES';

export const RECEIVE_CASTLE = 'RECEIVE_CASTLE';

export const NEW_BID_FOR_THIS_USER = 'NEW_BID_FOR_THIS_USER';

export const FETCH_CASTLE_BY_CATEGORY = 'FETCH_CASTLE_BY_CATEGORY';

export const USER_BIDS = 'USER_BIDS';

